#ENC[AES256_GCM,data:9Ms2U3PmhWEsoX0clcTuocdDafcg3uwseEKSQ2/iHrEENmFWZ27nkraWfoMbtg==,iv:hfYi/39ND2BFPBS8CqjcxynbrZXp0ejnC8Uj3MVPVTI=,tag:p6vZmo4W4Fmsl849q7+iug==,type:comment]
#ENC[AES256_GCM,data:xBTYZjoN4BqO0PaxNvdbvx4p35KBWnPCSdULPrq4iVZZJxPp+cnvOsU3T2mAh5JXcNqMVkGfWDg=,iv:gyyRsCDF62BqFPZ+HSEkAN/OjcFKjZLiawTn552/P4E=,tag:Prm9LJdP5pzK8T6NrBvJRA==,type:comment]
secrets:
    nbot:
        enabled: ENC[AES256_GCM,data:Eiy7QA==,iv:4v029GmNahs4JU/W/Mq36izCXHqsV/jQVB7rctALNdg=,tag:Z1QBmGnjqh1Op1nL/+Epww==,type:bool]
        stringData:
            TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:KPpr4eorG0RMr+LsHlp1QsZ/3PFIVkryOemTZkCZhQiC+1EPMunBQVbTQH+ccw==,iv:Jxg1lqzlRcm360Vb/86y24fQVqrfxmf/8bCg0Vg9060=,tag:bYMMv6c7g8c0iE3pDgjwwg==,type:str]
            QBITTORRENT_USERNAME: ENC[AES256_GCM,data:LbklG18=,iv:BdELyqj6W2MjS3YAiRE729yMKzelm+lafeJRTsjCJxY=,tag:IZ2eYcaiUWJbFwT4thhXEw==,type:str]
            QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:PUmUDMXcOvGJUl5B,iv:6P3LexqAL64+wqFxY3neKfZvUgb8eE6rtP2jUfcNrR0=,tag:N6u6xwzOvigPjczGyvlRwA==,type:str]
            ALLOWED_USERS: ENC[AES256_GCM,data:071OrUexxhbD,iv:/HLkT68J+uXDbsvi03A0Y8+Fahn9Spy5SjDhrTvBa1o=,tag:XyyvDyPu2uYygIvSdphsUQ==,type:str]
            SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:jcNknXiZvQGo4AwW/dbNcLQCUrQ=,iv:LgeTJrDPPK5qZA8isnzu3dv8iM9VU9fR2o6K8lTssYU=,tag:htm0Slie2BoEX5N9ARP/mg==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cWk1T3VPNjQ3SFMxSFky
            RzlLQ3llV0o3V2o3RE5MeldzNkNmN01Bcmc0Ck5NVm1JVWNKT1hnd2hDQVoyM3Qx
            VCtDS2JWSnNGZUFGSWJSVmdtVjhsYlkKLS0tIEgzWGxzWUdmTi9BamhFZWFnejdZ
            U2RpZHo2Q2RRU256UzZ2QUN3bHRIN00KYnzhTIucp/IiGscqBhfC/rp/Ld+crjOA
            9Nh9GWwiMCHBRMq7oyh8gEB7fi5GZY2bgR6aD7r/ajY6inJwibhDBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T14:55:05Z"
    mac: ENC[AES256_GCM,data:9a2r4PPjDnZcuPcrEZZdZdMpLLG0ZYmavM9D7BEBzAM0F9rIzQ1uUwqHLYYvSnQdP+Ttx/iFJv77gC2N7dAk3IhCWcX/+RbTYDfC/89ONnQu+oh8aNVtJMER4gvwR5phJpX9pJHP27QOMPT32VUaQpc6luLioz0YsFf1Q0toNrc=,iv:3k3kjpDaumMQMOJ7zszbjkQ0oTNv1hy0mFMcwbnvNbg=,tag:PP/C48D6jA+6nM5A/KZ7NQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
