#ENC[AES256_GCM,data:L3nU0wfyosDmZjWkuZcbjgFwoXwEKNvaF5ImqHpxD3mhyNL2Py/RZ2GNThKiNw==,iv:kja8SJ9oYoVFPBaonGc9nojDT7CLq6EQf1EtKlh74oo=,tag:wXgNHnBv5+sOP3MLYVYbLg==,type:comment]
#ENC[AES256_GCM,data:HpTCcPzPRBJ/nelzO30G4/zZnNVSLXh97IYhQdNbNpZKv7lP748P52XvQd4EDc7YJekMXTcm/Sg=,iv:LfBGXbRWOBne812uJqOdbHh01hhvgOKwRcqST05MMq8=,tag:0RCspFlTy4nfzpiogA0i2g==,type:comment]
secrets:
    nbot-secret:
        enabled: ENC[AES256_GCM,data:/OQnVQ==,iv:x3dXFLx8kwnb5KSWpo2waU/aNm9aRFPnjg8wP7hUfME=,tag:3+RfkL1O/dJ4xdGJ5MeRWQ==,type:bool]
        stringData:
            TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:lGteNTbKNdsl4zetywEvYlajwuc=,iv:muZl+85vYqmmi2n1np4hWkTbfYYg67QQ+7fiZt3EDfc=,tag:AdCkTOJuLwZPgHkl8cIdNA==,type:str]
            QBITTORRENT_USERNAME: ENC[AES256_GCM,data:WWYY+UGEbiQSwCOO6keDp7nkMA==,iv:Fl2kIhxMdP2hL1/5BGf7x/m7+mxyW7GK9WMLD560wO0=,tag:KhOJy4gVhe4W7jAj2iTung==,type:str]
            QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:6E5EoS17FVB+vyZ+Fi76wSluLA==,iv:dYA5D0YAzN5P/PCNLI7cTxC461LLTyoa+CQomWcmoUQ=,tag:ivgai/B4Uibi9qZBvEogfA==,type:str]
            ALLOWED_USER_IDS: ENC[AES256_GCM,data:HbuVLaLG7bNf/Qcgee5nknPp,iv:gfQ8GF5QcxpDM2DlozjzKmJhQlmpWBLy57/QOefutwU=,tag:lrHQInkpxnyFnevKaIC1Ow==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MjBPeURFcWpMRTJwMit1
            ZGlFQWlnaGRYRWM2Q1MrdUh2ZkswNnRibVV3CmFWd2N4dTdxS09JbERWMEZtRmR0
            ZEJtRmhaa1A0bFVURXNJMEl1dzlPZGcKLS0tIHZDbWhheTU5Q2d4Ymk5VVo0UjRD
            ZkNNaTdWVTZac2EvU0Nhc2Z3b291ZDgKhUSqWPDoK+Vwf5R4o5FYNHQhf1vUrrLY
            gerWaNl2nQThQVoqh0RpR/Bzsfh/OrjhGiJWzbLgsH6s2mbl7Xsd9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T13:53:13Z"
    mac: ENC[AES256_GCM,data:3ep0fCZ7bpUcMDd2RpOlI7UFgGaqdNBV/ygYd+6XbYTNUouJ3iPTdpMbpqvUUjue9yAGJFWQMreRBVAtwTAXD+52o02sNDL52GdzIblyccSeOe+x37CF18ganFaTSZgUvFF+klmqMU/R996myEbio4rctMoRhFCc5U1j8OkNYyo=,iv:TNvpvRbOLaurwlLcX1AhhcNZXIHpdmZvbbizRv10XPc=,tag:eIM2VyQLdUc5HmjEIHiaHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
