#ENC[AES256_GCM,data:7sX/xYq0Vls7C3X1mhiVBo8bFYfYFZIyAbqvJ7KorQ/gr+P5vpuRbWch+3YWeA==,iv:9ivvwrHDcthZIZv/fruPvzEO+TbP2ESCGue/zyxoBZ4=,tag:nQWV8AZnzYvDn/ZmCXu+9w==,type:comment]
#ENC[AES256_GCM,data:jt1YLSiWjHgWP/Ic21zxeF8c55b2lioUPAi/A7XRUl0fKecGuITvk4DYAEgOSwh8u99jA9f3kPc=,iv:175W1Uw/j+cMnLF/sGjnAIT7nN3cyYeQbD8t5HFE8IU=,tag:Q5jh/kt0Dsh/G3mIHZSy7A==,type:comment]
secrets:
    nbot:
        enabled: ENC[AES256_GCM,data:7wYWvg==,iv:19RpV9udiOZ04G48pMOqliHBUKPkye9Vv0NdmZqAuBw=,tag:oQXIDpFi34Bi1/jHDKHA4Q==,type:bool]
        stringData:
            TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:lZtAR1XSHRAuQjOtKt6Em3hX3qF6wKKs+JFPbPJ9vWPdLXNiMt5ySfKvFcni1w==,iv:wQmZXo8zWva6YeCOIRPABwaiCRiacpjsYS8ddn0/ojA=,tag:wPduZMnaemJRYnSszxBPcw==,type:str]
            QBITTORRENT_USERNAME: ENC[AES256_GCM,data:4qcQEh8=,iv:dZfS7ZgNcypiB4fCds1xRrl+wFrXAsE+zu7YmT1XOGs=,tag:nl3Ai2qmM/7rvuK2AcFeJg==,type:str]
            QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:oL5nTEMA/wEJtHG1,iv:bCFV1vpXYwbFbo2bq0FnbXWVXHEOBNV7WA7khKNQTmE=,tag:IEmNplePYPEPJFIPv32xZg==,type:str]
            ALLOWED_USER_IDS: ENC[AES256_GCM,data:XUmi75+IwhlZ,iv:gX1uWdQgAaiwto0T+xvggrOmxXdWDAXzlYSbGczM5Iw=,tag:4KVyEkkP0qJzI3DTawhiQQ==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNHJMRE9IYnc5dTNENXNn
            bFZndENpUFZtdEFmQmpsZDEzZWg0WHF1ZlNnCjlJaFdqZ3N0dlBxNGZSZXhSWHVQ
            ZkRBUTU1aTdKSW9SMnoxUmxwbFZXUkUKLS0tIHNtcjhrS1NvOER3OGNySUJtNEht
            MnNBVXoxQTY2RWIrekZYVGdlemUyOTgKPNaGgYAILNYbkO5RDI9j5unkxenCY4sm
            O+VVuwb3yKY9YP5sJt8SssJwkgu3Y+8z7raYgvxXp7JgEDHW3KzL8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T14:10:47Z"
    mac: ENC[AES256_GCM,data:i/7R5c7HL6EWyLx0zuJjluK1lMvqpwgCwu1bpV8jAjvzaXpcbFZ3SZppas0FSZUJmYhUZqibbx/j/J6cv19Cac8sENGwXy6UnesC4vZF3yNGLzRoZ3NE/rd3Lasj12NoJI+OjknxAxU4OP73ga8Mvj5n7j73zB9OJAshgCCOjJc=,iv:3UP/POi1FEV6BrTzkbv5OgV5RuaChAUklvaTf1lZZXg=,tag:U/DzIapfUVUndO+rucH7ZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
