repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: raw
    url: https://bedag.github.io/helm-charts/

---
releases:
# Distributed storage between clusters
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.9.1
    values:
      - ./longhorn.values.yaml

  - name: longhorn-ingress
    namespace: longhorn-system
    chart: raw/raw
    version: 2.0.0
    values:
      - ./ingress.values.yaml