repositories:
  - name: longhorn
    url: https://charts.longhorn.io

---
releases:
# Distributed storage between clusters
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.9.1
    values:
      - ./longhorn.values.yaml

  - name: longhorn-custom-definitions
    namespace: longhorn-system
    chart: ./longhorn-custom-definitions
