apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - deployment.yaml
  - middleware.yaml
  - ingress-route.yaml
  - pvc.yaml
  - service.yaml
  - configmap.yaml
  - matter-pvc.yaml
  - matter-service.yaml
  - matter-deployment.yaml
  - mosquitto-pvc.yaml
  - mosquitto-configmap.yaml
  - mosquitto-deployment.yaml
  - mosquitto-service.yaml
  - zigbee2mqtt-pvc.yaml
  - zigbee2mqtt-configmap.yaml
  - zigbee2mqtt-deployment.yaml
  - zigbee2mqtt-service.yaml
  - esphome-pvc.yaml
  - esphome-deployment.yaml
  - esphome-service.yaml

# namespace: home-assistant

# Refer to: https://github.com/mysticrenji/home-assistant-on-kubernetes/blob/main/home-automation/deployment.yaml
#  for extra ideas