---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: secondary
  resources:
    requests:
      storage: 1Gi