controllers:
  main:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: couchdb
          tag: 3.3.3
        env:
          COUCHDB_USER:
            valueFrom:
              secretKeyRef:
                name: couchdb-secret
                key: username
          COUCHDB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: couchdb-secret
                key: password
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 5984

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /opt/couchdb/data

rawResources:
  ingress-route:
    enabled: true
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    annotations:
      external-dns.alpha.kubernetes.io/target: 192.168.1.200
      kubernetes.io/ingress.class: traefik-external
    spec:
      spec:
        entryPoints:
          - websecure
        routes:
          - match: Host(`obsidian-sync.naguiar.dev`)
            kind: Rule
            services:
              - name: obsidian-couchdb
                port: 5984
        tls:
          secretName: certificate-tls
