apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tinfoil-hat
  labels:
    app: tinfoil-hat
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tinfoil
      port: 80
      targetPort: 8465
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.qbittorrent.service.bittorrent.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: tinfoil-hat