{{- if .Values.gluetun.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpn-secret
  labels:
    app: qbittorrent
type: Opaque
stringData:
  VPN_SERVICE_PROVIDER: {{ .Values.VPN_SERVICE_PROVIDER | quote }}
  VPN_TYPE: {{ .Values.VPN_TYPE | quote }}
  OPENVPN_USER: {{ .Values.OPENVPN_USER | quote }}
  OPENVPN_PASSWORD: {{ .Values.OPENVPN_PASSWORD | quote }}
  SERVER_COUNTRIES: {{ .Values.SERVER_COUNTRIES | quote }}
{{- end -}}
