configs:
    baseUrl: ENC[AES256_GCM,data:CeiO0JbV30mz9g7rU3vLDna3myOLgg==,iv:bkc8gwm4Jjp9vLE+jU55mTsxOD8kA4WvimJTmP8ORQA=,tag:YcarQtJD5a1powDkoYZgEQ==,type:str]
    values:
        - ENC[AES256_GCM,data:abaZSIIrE40Sgj0=,iv:Y8NU9DWDFMhUPL/9Bx5xrapEdU/WZM7Jji9GLus3FYY=,tag:70msQGxgE7BGRkdkfVi4SA==,type:str]
        - ENC[AES256_GCM,data:KVDs3fX5ZPQ597Bs,iv:5jG+Ejdvxv3xsLo8SLNuGrzM1f8PzzYomguv4aVRrkE=,tag:TKUOFWozb0MSZRBoD0ky7Q==,type:str]
        - ENC[AES256_GCM,data:CVGWQQUYlMDi/Q4=,iv:Wv1BgTiLlnRUSFJs9BZYMfMGRFHI5ew0cl7Gazc/zM0=,tag:Lk87gd9f4koF4hn5PzpfPQ==,type:str]
        - ENC[AES256_GCM,data:p57LjkLKgMEr+wXzDi7EkVIrBbxy,iv:AodWWM3a45S5+1cZ+sYhrcn096K7e5qfKGcJR29anS8=,tag:kDkS/8GgLuaY+lYdn0lvWw==,type:str]
        - ENC[AES256_GCM,data:wuDFas/SW5Orpvu5UQ==,iv:NMkNrWc86ZWKQXbqnLUi7XckrCnAmLOqU3BjGqX+fCE=,tag:HQiv/1iilnUMwnFE1TQo5g==,type:str]
        - ENC[AES256_GCM,data:SA1hh4OpNoGW+oCHjMS/aY8=,iv:qk/UqCUjcKJsAAPBiwn2E4/rmIVm27cCVIkREGqWf/E=,tag:UmKQ9l6VpxSCthOKSzZbfA==,type:str]
#ENC[AES256_GCM,data:imkKIS5r6cE57Jg0EBHbuExCHDQ+hg==,iv:sG/GOUUjUB9IywznwDHEqylKdjJmHb7foLfVWKaTKX0=,tag:wJvaJhXR92krK4nE992PdQ==,type:comment]
#ENC[AES256_GCM,data:OzeQt164QpVfXMzm/sCCLI5Sxy0=,iv:553NpNeRFOAIBF2CHqdWQDrIn2Bc2Dhn9znpk7Fvaks=,tag:2Od5ebOn7F/IRJ5OyF44Ug==,type:comment]
stash:
    token: ENC[AES256_GCM,data:V0K7MEJenaQyGADQmMuV+c7JmXYoBztzG+yaPI1eZLsLEzVkN9sAGVLFlZWZSx3cwBjT8JJIE3BL4ccGDS7Uar1prbMHZanDvHHQSG69C/aq8arSdmpS75N46nB5z7RRwNWIhz3E6r8ex1gn7BZ5FKsZa5kwKQYtDE+z9EuC0ZCDCu0MUsyN4xxuwL9Bj493,iv:MZMsXpsMNlSV8yYdwSN/FRp2DaL27UqWGiaE6C/xbP0=,tag:vV/9kO3eeSRB/s1z8t7tAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZjVRa2xWVWViSTQyQkJn
            cnc2blA2bTlhYVdKelZPVlhZODluZDB1ZG1FCkMvWlY0Zm9kY1MyaXAvRXpEQ1Aw
            Ymp1WHkzUTQ5enR2UEdGVys2S0N6c0kKLS0tIDcxSy9XZk11c3RwWTNxVEZ5NFlB
            aEp6QTU2OHROWDNnTWF4elpUSVF5ZjQK9PbWmyz7bOVIhyeportg3UeEdo0Qaiqa
            KQRcIoNl/oVuPKr+xhEznllo6jRDLM/AwEvMJuxyqZW2qn0TQygAAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
    lastmodified: "2026-07-17T03:10:01Z"
    mac: ENC[AES256_GCM,data:PmWvr03/4HTNA9rgUkje2XIf5lzQtY4EFOLMHz2A+czMVqb3hpGReGBvt4ktwFwt1CTNer7b+ZQniCcAv+KTycaG+Jr1WPTEIZojNL5oUJA+VLHpv/jGaQqFl3rJuu05+uVkQABlaki6Mr2oLzfE2/o/FGl/L755SobMs/wnEWo=,iv:gYumjFK/O19Bzl4FbSA2sQ71kCRX7cUCUQHSbf/CnEA=,tag:uxH0FnErWtYHMz/Ivvrj8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
