configs:
    baseUrl: ENC[AES256_GCM,data:TydDK7Ccgqy5JUMVl32tQ0guyK+oRA==,iv:gj9Lu5rbZ0NX52Ag9pT8rEHmQ7Q78iYAaSdO934Ytl8=,tag:w/2bwyZ3+Sj1QgmZuE+wow==,type:str]
    values:
        - ENC[AES256_GCM,data:HmuDD+NX5Dr3waI=,iv:PkErC8EzoIvU0qrbsOqoFj+D5ao0F8ELTx60Znh54OY=,tag:piffHttkjt7IVt83K5jHxw==,type:str]
        - ENC[AES256_GCM,data:VpOz1/AJZ7FfpH8F,iv:dtAyLowVD4/CA4h5cZfqxgvz4Cj6oGIedgwtEwN4FPg=,tag:/i7tMsEv3EtopqKcU0E2tw==,type:str]
        - ENC[AES256_GCM,data:ICzm/rAUbrm7kf4=,iv:29cHisqs7POtsOpl7d11dvGuzoNxiRr3eD+d7gqtxVI=,tag:pKM8bY2ZWZs7wz2q+kMJzA==,type:str]
        - ENC[AES256_GCM,data:3DnfntHQqapu,iv:1mHQmGr1V6BA6hOHZcxQR8HhVVqKRAPW9tQO8MHcBWU=,tag:S1uqMLZhtCTSUGE8M4dd8w==,type:str]
        - ENC[AES256_GCM,data:Yg+8zr1gQAHMvBU=,iv:u6QJTt7GfmirfdcA/Yf/sjsEtZR3WCXCH7NLdGFcMJc=,tag:lGSWtATc3QgqAPtXCL86Iw==,type:str]
        - ENC[AES256_GCM,data:cI1STsIX7sdZQQuAgTUVcnv8BQ77,iv:2zb8cs7ZYNmBPFgE4q+r0OfEUBYwdE3Sq0K6qMkh5PM=,tag:bFAkHoUxnpVPEFk+3zqCFw==,type:str]
        - ENC[AES256_GCM,data:OVoIooLrY38O,iv:CRs148/LhD3W6IE/XeRA3UMyCh+VsBpyo/FqcpCNd7Q=,tag:UCskUEygt9R5sb51MYzNfg==,type:str]
#ENC[AES256_GCM,data:Dhrleosp7JQlBDa73X/FZNeJDqe9Jw==,iv:hBidKF9GN4SCTAz5gWyXidwvvNxfHt1jyo8+bczIDX0=,tag:EizejzibjAnkJL8nKiXNiA==,type:comment]
#ENC[AES256_GCM,data:KmEP7ke8sqIqXJaDyMfQ1G9WSMU=,iv:C0bmY5htQP54toqZQiZyepvNtJEQJz9fOJuetNukVpM=,tag:KxliaYQNz8W1wHzIYn9s6w==,type:comment]
stash:
    token: ENC[AES256_GCM,data:J8pAxZVVQt4fiVPl3PgLqvvF5X+MUhbO4Q5Y8Zbwd8PUBB+WTcOin3GH8suoNjTM/Lk8n8HtY2kTpj+XqUc+b5qGW7pcY+j/75qa5KGBCQHIV00n3IhA+QQZhBjlT34rijZ+3E2KDJhaHT6wh2G77TFRED++hclAlpggp4AJsFtb//ODb8pOKnFeNB947ZZM,iv:UeX9+MjSkg9EOwI60J86Ygyh8JK6cR/pHnsDp6BQU0s=,tag:KRe7QzYUm/juOpxGxkifxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQTBUa1F3TEdHQ01NVzEy
            TmVvenc1MGdQVGVuVDFDRUs4ZU1EVlBFQnkwCjZnMUFJTWxtZXQwbGRuZ2JJT0tM
            b0kyWEozTnpwVGI3TDZ4VHRaOXZOZ1EKLS0tIHZUOHVud21ZWitSTFI1U3MxWlNi
            dVVyNjV5elcyb2JZdVdjcjJKdDdJMlUK/hwusvEBDuMZfElBf6aqTExRgl8oDmCE
            mcwYyab3baw+/yShv7cG0LX5kCR2J2+5GdBLDGYDuL3LsReO52vi9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
    lastmodified: "2026-06-18T21:13:39Z"
    mac: ENC[AES256_GCM,data:HmIcPCfVTVETXPwokfj2qMmo9wombSDea1SEJcX0phuJAboRkPU42hHewYUAgZ4LWHX77evJkgNyPjVZ/niZsJvoR6HziL9BDaKi61iWl5GGLcWPN8Q16MOaNnXSm6Zzk2fyoccZlpTuKfRfaD6fja42EZj4bFenQ8AvK1U6+SM=,iv:MFH/cZRa64xHye1H0HcDB6jvmsxJ8YVxezjqiRuXbwc=,tag:fQrA8dsUWCgmrcqWKcqFPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
