apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-daily
  namespace: longhorn-system
spec:
  cron: "0 3 ? * TUE,WED,THU,FRI,SAT,SUN"
  task: "snapshot"
  groups:
  - daily
  - default
  retain: 6
  concurrency: 2
