## Common Labels
# commonLabels -- Common Labels are added to each kubernetes resource manifest.
commonLabels: {}

## Overwrite Labels
# overwriteLabels -- Overwrites default labels, but not resource specific labels and common labels
overwriteLabels: {}

## Define Pure kubernetes resources
# resources -- Define resources to be deployed by the raw chart
resources:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: gitea-postgres-postgresql
    type: Opaque
    data:
      #a5Y5ndbu2oiUnG
      postgres-password: YTVZNW5kYnUyb2lVbkc=
      password: YTVZNW5kYnUyb2lVbkc=
# templates -- Define templates which will be executed using the `tpl` function
templates: []


