# k8s/10_apps/10_nbot/values/nbot.values.yaml
controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/nilson-aguiar/nbot
          tag: 1.0.0
          pullPolicy: IfNotPresent
        env:
          TZ: Europe/Amsterdam
          QBITTORRENT_HOST: "http://tinfoil-hat-qbittorrent.tinfoil-hat.svc.cluster.local:8080"
        envFrom:
          - secretRef:
              name: nbot
        ports:
          - name: http
            containerPort: &port 8080
        probes:
          liveness:
            enabled: true
            port: *port
          readiness:
            enabled: true
            port: *port
          startup:
            enabled: true
            port: *port
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  app:
    controller: main
    ports:
      http:
        port: *port

rawResources:
  ingress-route:
    enabled: true
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    annotations:
      external-dns.alpha.kubernetes.io/target: 192.168.1.200
      kubernetes.io/ingress.class: traefik-external
    spec:
      spec:
        entryPoints:
          - websecure
        routes:
          - match: Host(`nbot.local.naguiar.dev`)
            kind: Rule
            services:
              - name: nbot
                port: *port
        tls:
          secretName: certificate-tls
