repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: raw
    url: https://bedag.github.io/helm-charts/

---
releases:
  - name: grafana
    namespace: grafana-system
    chart: grafana/grafana
    version: 10.0.0
    secrets:
      - ./secrets/grafana.values.secret.yaml
    values:
      - ./grafana.values.yaml

  - name: grafana-ingress
    namespace: grafana-system
    chart: raw/raw
    version: 2.0.2
    values:
      - ./ingress.values.yaml