apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - middleware.yaml
  - ingress-route.yaml
  - pvc.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: homeassistant/home-assistant


labels:
  - includeSelectors: true
    pairs:
      app: home-assistant
      app.kubernetes.io/name: home-assistant

# Refer to: https://github.com/mysticrenji/home-assistant-on-kubernetes/blob/main/home-automation/deployment.yaml
#  for extra ideas