secrets:
  vpn-credentials:
    enabled: true
    stringData:
      # For Mullvad WireGuard (recommended)
      wireguard_private_key: "YOUR_WIREGUARD_PRIVATE_KEY_HERE"
      wireguard_addresses: "YOUR_WIREGUARD_IP_ADDRESS/32"
      
      # Alternative: For OpenVPN providers (comment out WireGuard above if using this)
      # openvpn_user: "your_username" 
      # openvpn_password: "your_password"
      
      # For other providers like NordVPN, ExpressVPN, etc. (comment out others if using this)
      # username: "your_username"
      # password: "your_password"
      
      # Optional: API keys for some providers
      # api_key: "your_api_key_here"

# After adding your credentials, encrypt this file with:
# sops -e -i gluetun-vpn.secrets.yaml
