ownfoil:
    secretKey: ENC[AES256_GCM,data:Iumg11gwmejp,iv:Z3ahUhRAhdPaicmerOjWbU/847aSadpy4pLc/eZ6YcQ=,tag:wg8x231t2IrSoOH0eNO7xA==,type:str]
    adminPassword: ENC[AES256_GCM,data:Uv6K59g=,iv:f7eAWjnjTFK1xuvqAOFdP+eGc3KYwAtjptzjI7i7Jgs=,tag:/WZjy0Br2bAsFDXr8YyFYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZlNqK3ZJSlBqN1AwSFF5
            TkNYWCsvSzlYdUJSQk9KaGFnREtWOXdxMmlBCkRBYWJLMVlTVEdxaFRZblZyeUJI
            MzRESkxTekVQS1RwaE5DUmFneHMxL3cKLS0tIHArMzhWdkkwckIvQ2xIZWp3Ty9I
            M2FQQ1VadlRNWUxUdTFGbk5Nczdzd3MKdWv6VO+2CrpvWFybN/oe3YgSiQW6jEl4
            ZY4WvC1GIZEXRvprCLydooZCSlEhsh/DpX2qEncrYuznpmoAgiQthA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
    lastmodified: "2026-07-29T07:11:02Z"
    mac: ENC[AES256_GCM,data:Fr3yEQuRfTOKG8cGSETfvrST2LqCH8GylD6kZE2q373SxXpJSdYYgyfSWAMTnqwtArlnXOh1zyGOUe6zAnO/vWHe7UW36jFgTEt2f/N+HGr3ygvRlXry0QKt/EPk5bR6PmuM4xNm0xhj4PknlYEq+YdHHzS2FsOALou2HQxpFg8=,iv:H99EiSkfIv7WXsgEDdRo4hBx5Ah68rEvOdrRNoVdDnk=,tag:V4OLOosQqWRU+BQGe2JbAg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
