controllers:
  overseerr:
    replicas: 1

    pod:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch

    containers:
      app:
        image:
          repository: sctx/overseerr
          tag: 1.34.0
        env:
          TZ: "Europe/Amsterdam"
          PORT: 5055
        ports:
          - name: http
            containerPort: 5055
        resources:
          requests:
            cpu: 25m
            memory: 256Mi
          limits:
            memory: 2048Mi

hostSuffix: &hostSuffix "local.naguiar.dev"

rawResources:
  ingress-route:
    enabled: true
    apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    annotations:
      external-dns.alpha.kubernetes.io/target: 192.168.1.200
      kubernetes.io/ingress.class: traefik-external
    spec:
      spec:
        entryPoints:
          - websecure
        routes:
          - match: Host(`overseerr.local.naguiar.dev`)
            kind: Rule
            services:
              - name: overseerr
                port: 5055
        tls:
          secretName: certificate-tls

service:
  app:
    controller: overseerr
    ports:
      http:
        port: 5055

persistence:
  config:
    enabled: true
    size: 5Gi
    storageClass: longhorn
    retain: true
    accessMode: ReadWriteOnce
    globalMounts:
      - path: /app/config
