controllers:
  seerr:
    containers:
      seerr:
        image:
          repository: ghcr.io/seerr-team/seerr
          tag: v3.2.0
        env:
          LOG_LEVEL: info
          PORT: 5055
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi

service:
  seerr:
    controller: seerr
    ports:
      http:
        port: 5055

persistence:
  config:
    existingClaim: seerr-config
    advancedMounts:
      seerr:
        seerr:
          - path: /app/config

ingress:
  seerr:
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: seerr.local.naguiar.dev
        paths:
          - path: /
            service:
              identifier: seerr
              port: http
      - host: seerr.naguiar.dev
        paths:
          - path: /
            service:
              identifier: seerr
              port: http
