apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

# namespace: home-assistant
images:
  - name: homeassistant/home-assistant
    newTag: 2025.8.3

#patches:
#- patch: |-
#    - op: replace
#      path: /spec/rules/0/host
#      value: example.com
#  target:
#    kind: Ingress
#    name: home-assistant
#    version: v1
