apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  env:
    - name: TZ
      value: Europe/Amsterdam
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  storage:
    size: 32Gi
    storageClass: longhorn
#  superuserSecret:
#    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: false
