apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9
  env:
    - name: TZ
      value: Europe/Amsterdam
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover
  storage:
    size: 32Gi
    storageClass: longhorn
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: false
  bootstrap:
    recovery:
      volume:
        persistentVolumeClaim:
          name: postgres-backup