apiVersion: v1
kind: Service
metadata:
  name: postgres
#  annotations:
#    external-dns.alpha.kubernetes.io/hostname: postgres.devbu.io
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16
    cnpg.io/instanceRole: primary