apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-monthly
spec:
  cron: "0 2 1 * ?"
  task: "backup"
  groups:
    - monthly
    - default
  retain: 1
  concurrency: 3

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  cron: "0 3 ? * TUE,WED,THU,FRI,SAT,SUN"
  task: "backup"
  groups:
    - daily
    - default
  retain: 30
  concurrency: 3

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-weekly
spec:
  cron: "0 3 ? * MON"
  task: "backup"
  groups:
    - weekly
    - default
  retain: 4
  concurrency: 3

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  cron: "0 4 * * *"
  task: "snapshot-cleanup"
  groups:
    - default
  concurrency: 2

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-daily
  namespace: longhorn-system
spec:
  cron: "0 1 * * *"
  task: "snapshot"
  groups:
    - default
  retain: 7
  concurrency: 2
