extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
  - --dns01-recursive-nameservers-only

global:
  leaderElection:
    namespace: cert-manager-system

replicaCount: 2
podDisruptionBudget:
  enabled: true

prometheus:
  enabled: true
  podmonitor:
    annotations: {}
    enabled: false
    endpointAdditionalProperties: {}
    honorLabels: false
    interval: 60s
    path: /metrics
    prometheusInstance: default
    scrapeTimeout: 30s
  servicemonitor:
    enabled: false
    honorLabels: false
    interval: 60s
    path: /metrics
    prometheusInstance: default
    scrapeTimeout: 30s
    targetPort: 9402

