repositories:
  - name: bjw-s
    oci: true
    url: ghcr.io/bjw-s/helm

templates:
  bjw: &bjw
    namespace: obsidian
    chart: bjw-s/app-template
    version: 3.5.1

releases:

  # 1. CouchDB for Obsidian LiveSync
  - name: obsidian-couchdb
    <<: *bjw
    secrets:
      - ./secrets/couchdb.values.secret.yaml
    values:
      - ./values/couchdb.values.yaml

  # 2. Obsidian Remote Application
  - name: obsidian-remote
    <<: *bjw
    # secrets:
    #   - ./secrets/obsidian.values.secret.yaml
    values:
      - ./values/obsidian-remote.values.yaml
