repositories:
  - name: cloudnative-pg
    url: https://cloudnative-pg.io/charts/


---
releases:
  - name: cloudnative-pg
    namespace: cloudnative-pg
    chart: cloudnative-pg/cloudnative-pg
    version: 0.22.1
    values:
      - ./values/pg.values.yaml
