## Common Labels
# commonLabels -- Common Labels are added to each kubernetes resource manifest.
commonLabels: {}

## Overwrite Labels
# overwriteLabels -- Overwrites default labels, but not resource specific labels and common labels
overwriteLabels: {}

## Define Pure kubernetes resources
# resources -- Define resources to be deployed by the raw chart
resources:
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: traefik-dashboard
      annotations:
        kubernetes.io/ingress.class: traefik-external
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`traefik.local.naguiar.dev`)
          kind: Rule
          middlewares:
            - name: traefik-dashboard-basicauth
              namespace: traefik-system
          services:
            - name: api@internal
              kind: TraefikService
      tls:
        secretName: certificate-tls
# templates -- Define templates which will be executed using the `tpl` function
templates: []
