repositories:
  - name: longhorn
    url: https://charts.longhorn.io

---
releases:
# Distributed storage between clusters
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.6.3
    values:
      - ./values.yaml