---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
spec:
  # Range between 129-254
  #  https://jodies.de/ipcalc?host=192.168.0.129&mask1=25
  # So I can configura my DHCP to allow:
  #  - Wireless devices            -> 192.168.1.5   - 192.168.1.99
  #  - Manually configured devices -> 192.168.1.100 - 192.168.1.128
  #  - Metal LB services           -> 192.168.1.129 - 192.168.1.254
  addresses:
    - 192.168.1.129/25
  autoAssign: false

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - pool