repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: bjw-s
    oci: true
    url: ghcr.io/bjw-s/helm

---
releases:
  #  Ingress for local network
  - name: ingress-traefik-internal
    namespace: traefik-system
    chart: traefik/traefik
    version: 33.0.0
    secrets:
      - ./secrets/traefik.values.secret.yaml
    values:
      - ./values/traefik.values.yaml

  - name: traefik-auth
    namespace: traefik-system
    chart: bjw-s/app-template
    version: 3.5.1
    secrets:
      - ./secrets/auth.values.secret.yaml

  - name: traefik-extra-resources
    namespace: traefik-system
    chart: raw/raw
    version: 2.0.0
    values:
      - ./values/extras.values.yaml
