secrets:
    secret:
        enabled: ENC[AES256_GCM,data:1W7Dug==,iv:kHygxMF0wctNI/5+aHarmWKHc7+p1VthmwAQuVvW20M=,tag:XJKbCHD4yHW0tXmqK5UTEQ==,type:bool]
        stringData:
            users: ENC[AES256_GCM,data:ifWdxQU/dtuOUXByAacXY+86iJuiNyd3XYqt5oklq61RSxknq2Gyxt4nxR8E,iv:ipHZPKufjG/eSxH+AzULBJpbyoM6eBLuFrqlH3WYrC4=,tag:YuF+Xrlmfp5dUqciPDvW/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWEYxcWh3TVlhbEpzNEg5
            TjZXL3l1WWN4OURHd0YyajNLYUlIam10L1hVCmU3T1FvL2ZDL1RmWEpvdGRQYk10
            ZkR3b3ZPOVZZV05yYjYwaVNGMXFmR1UKLS0tIDdMVElHKzgreXRPb3BXMndvOTZK
            TVVlOHd6RDUydkRpTDFyTXdyVmhUMncKmqWOoR4G133Dp43vl/YKSvWi0sk76RCI
            4kBI6TJ5SdbbkZpbdSLG0r6Vj5hTzjW/Gubs0xt7g2sg6HI8mRSjJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
    lastmodified: "2026-10-04T07:14:27Z"
    mac: ENC[AES256_GCM,data:2YSNSaJ8pKzmDTm83s1Okp5C35QpYUB1uUzd4M5HAMPgFwzlcuAbvd/0T5AxadGgiikUOd1/Qbj5xVQg01g/AtFGYwG6yECaCERL/7LTFWdQup6Z0JHvLO2u9HmhelkNDwTzte88RdHfX2aO961bNsqSqe5+d7QdWI/HUUUWg6A=,iv:5DeLTq6dxCPfYiyxYX3D4B2za88VUFJz8nrbeMAzs4Q=,tag:9s/JGqVeXx6r4xzz/obsQA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
