secrets:
    secret:
        enabled: ENC[AES256_GCM,data:FV49xg==,iv:DitMUGVVF5B6H5f+9UoXey2H1Zm5tsT9ntEufGaHcuM=,tag:LkxGD+VldSWJYMf+bAQB3A==,type:bool]
        stringData:
            users: ENC[AES256_GCM,data:k6f/f9AYZ4loT5gTkbUq+BvwYkCPTbn4IR97UUyBNx6zmpom8RA4WT8p/COF,iv:f/vGSSIDj1jHd3RRiTQnHLjgZbyWvskz5np84CDnaHE=,tag:8Km5JKEy8wK2ZVoFWfsNqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYjk4dXFYb1QxVjFQQlp1
            WHdiai9KYnliWVhDYkVFbU9acTFrNDg3cmlJCmR4SU9USW9vTUYzaVNreTVZbE16
            SUQxeU15cjd3a2RLVU5DR0xmd1A4cm8KLS0tIGVuYWg2NHJOZ1ZRZlE0Y2cvZEho
            K0pzYTNrM2ZXaFNRbGVPQnBLSUZTZ3MKcXfpf603SNUhPTjs0Fr48bZ9Im8krTcN
            MEFAh4DlwW4CHR7b4Z0dREmu0bF6fnymOkEQSLwIDJqC9o9IBWIe8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T19:54:14Z"
    mac: ENC[AES256_GCM,data:OILCpRJ75WvwF9cGYwLet/u2jmy2HfqXlk8CggkL1pCVRoDySx8uqe/sM6Rmdr2fhdhJSgQq5XNdw6LntxUiweWezvWYsOU5zdu2Sn4re3Tcs5GIk0zn2P5XMV8p530Uj953v9cUUUZ48Hu5Be7VlLyVDP0S6824Vbh8I9o4LS4=,iv:0Jly/aLlpDsAeBjsM/7YjyUpurgtVgSSJKPIESjEUlE=,tag:SLW634PiLWe0d60Yn30tEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
