providers:
    file:
        content:
            http:
                serversTransports:
                    k8s-transport:
                        insecureSkipVerify: ENC[AES256_GCM,data:VcPS23I=,iv:0BTvRfks+YDJo1cHSvppg8b6l8O85Uj+sJF8aWLW5Xk=,tag:DuyPlLz3xiyFcLgSAPJiWA==,type:bool]
                        rootCAs:
                            - ENC[AES256_GCM,data:HB80nmjeCrZSt1M/G+daWdi4J1HFu2fl4JAydyFthljHDof2/zwulxmmIWMH,iv:4FDXcNBVOlUcLv671rYUXNNohfKzEmFOpOIHQTosbV0=,tag:VXlYnQ9VuiRG5fLpDgznaQ==,type:str]
                        certificates:
                            - certFile: ENC[AES256_GCM,data:0gP7hXK4J8CJB4aVWQ3qF6w9xoClh1kKfpFHgpM9UiGRyAQMn3IzXQfh+Yfyr6A95sVIicrorLHGVQ==,iv:DXy5hrIT7aaIBQeny1oLdfDzC7ODxRJA04Y4/F609M8=,tag:8cq5GaZ31yAX24Fhfof04Q==,type:str]
                              keyFile: ENC[AES256_GCM,data:b+ywuEIJ3nitd2O4Fh4XIrv/Zbh1WBBysmi2bDlTUDh5ajz34AMTyP8CIAyF+D7AArIMreBUUEh2RA==,iv:48GJ3LoLIUv9ce/6hJpbkmOlhpCLKxIeUETl2lMPwAY=,tag:wMo+i1GLss9qUQcayjjAhQ==,type:str]
                services:
                    nlab:
                        loadBalancer:
                            passHostHeader: ENC[AES256_GCM,data:u9obiA==,iv:+i3gkDEdLOAU19vQw5KQ7f1BKHvLvjFSneWY+vmEri8=,tag:G6dytiHBmrJ++NqWFgb4EQ==,type:bool]
                            healthCheck:
                                status: ENC[AES256_GCM,data:tWno,iv:wWW+mHjVbszN2FqaPXAwfkMk2BNsdLpFgjOLAdtG2hk=,tag:IQ8RKCGi0dA9hBVxKHG7eQ==,type:int]
                                path: ENC[AES256_GCM,data:XgkCiw==,iv:PQMmau7pLNFvG0R1ZVdMSo1RXHRAsoPLFrkuHg01GV0=,tag:YheswpARBxFB57W1HiAk5w==,type:str]
                                interval: ENC[AES256_GCM,data:qTVG,iv:FfsQte7XdO/wSrHs71BHeesoQjhzEP+Dmx01hMF8Gis=,tag:NnIucxslfStgwtGYyCKtug==,type:str]
                                timeout: ENC[AES256_GCM,data:Xds=,iv:WmT8a+Lsi23nNhKUt1jWyyHQMgb4Oi+di01gY2qxp0E=,tag:n4MxmaCGAC4JqProR7HY/A==,type:str]
                            servers:
                                - url: ENC[AES256_GCM,data:kBTSAjf5gc8WQAmCdwaDQHDWgJEdkIf1zwY=,iv:v1vy3PoQA/hsaV+XLvKWIcdaK+YIB9/VINrrLAR7il8=,tag:UQtaPBgHwAEoBY0vR6qA0w==,type:str]
                                - url: ENC[AES256_GCM,data:CP/uuxQCrjwl80zbQGxuIozn4fVZ2j4lfkY=,iv:T/PFpMCwZe3YRKzLzBS4LwGSbgrioGeKdomOPFWBmQs=,tag:5Dcny054MQXb3HEIl0kgeA==,type:str]
                                - url: ENC[AES256_GCM,data:p+yxzHyJ/mKhcahcU52gw/2jbt0gbA1qkYo=,iv:X5MH/Fkt76CuF8Y2suKOWSJw2J0CEvOdSRZTvmrqnMY=,tag:+AGF5cqZ8VwcOK3ugXr51w==,type:str]
#ENC[AES256_GCM,data:eESgvhrLlWYGsXawwhCi5dzC803o8dDQ4nehvWlklQ==,iv:s4EUg1KCBHc+1bvpoF8QtLMNhmWQXDLBVzBqBuLK59E=,tag:6g/Ke4VsHVfGMszrcW74tw==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RUhqWDVNam9lLzZQdThR
            NGM3TWNNemkyWDNlck5GL0FObjFrUURaTFJRCjkvcGF0dVRXYUY1YVBtMUZpL0R6
            TlgwajdNR09hNGJHbVhaNXJZWktONVEKLS0tIFNMZG9Pb2gzcVVtWDNVZm9xZjJo
            N0phaGtaUGMyU2RERFlnVFJuenR3OFUKVm4rUtMLDz1jX5aXDsYUf/9asmSluz1Q
            rWwU6EQOxFh6FEV7OA8UtDC1eQNdJuexQhzPn6bUjzbsbQMox9CaEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
    lastmodified: "2026-10-04T07:14:27Z"
    mac: ENC[AES256_GCM,data:TTdlxu/7b9+HUkpHPCToSktmbZQLNysV9EUFmVx+CiQQtqA6j3KBOkU/QEzPVlnN/egAD75WuARXt0Ueg4Q28djCAd4SyxudFq/qp+kEZ45PS6zS6oa8WlzkKFne1tXGNFobMM16gdqMNuLbcAnwE0Mr2hl8uk4JgXyxEvQWr8s=,iv:G9c8srvktK3uWw5lg8xjmlE9gocR03UpbtXhvOLhSjE=,tag:mbWtBp/PqF6jIkRZjsFCxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
