---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-tinfoil-hat-pvc
  labels:
    app: tinfoil-hat
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if (eq "-" .Values.persistence.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
  {{- end}}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}