---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  labels:
    app: esphome
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{
          "name": "lan-bridge",
          "namespace": "kube-system",
          "ips": ["192.168.1.232/24"]
        }]'
      labels:
        app: esphome
    spec:
      containers:
        - name: esphome
          image: "ghcr.io/esphome/esphome:tag-here"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PLATFORMIO_CORE_DIR
              value: "/cache/pio"
            - name: ESPHOME_BUILD_PATH
              value: "/cache/build"
            - name: ESPHOME_DATA_DIR
              value: "/cache/data"
            - name: PIP_CACHE_DIR
              value: "/cache/pip"
          ports:
            - name: http
              containerPort: 6052
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              memory: "4Gi"
          volumeMounts:
            - name: esphome-data-volume
              mountPath: /config
            - name: cache-volume
              mountPath: /cache
      restartPolicy: Always
      volumes:
        - name: esphome-data-volume
          persistentVolumeClaim:
            claimName: esphome-data
        - name: cache-volume
          emptyDir: {}
