rawResources:
    nordvpn-secret:
        enabled: ENC[AES256_GCM,data:trP4Iw==,iv:Z9t+di+ge8j21vtMl1n9Hkb+cpfTML5erxF2MZEzHdQ=,tag:7rCUhcO2GRUOpNhCYJ/aSA==,type:bool]
        apiVersion: ENC[AES256_GCM,data:Nzw=,iv:4ge2QRrOBdHxGEYls5uzX6j+LNIaDCnv7Lgny8B3ABA=,tag:yeJvT/rgPEnbyw7dYoYucw==,type:str]
        kind: ENC[AES256_GCM,data:RcUlGpiF,iv:pxJZtO5pJEg8MByxF7fw/wU9EUG9NJ8ZjO8EZcpCn2E=,tag:AcqVlOSejZglgOA7h+RcSw==,type:str]
        spec:
            stringData:
                WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:V8nWVI4Iwv/KqEPoUShhqx9+lxmfL7KGwO6wjVuCGQs6gafSTGSYIreV65U=,iv:AyrikvA7QqsrJ6gtqhYIEAcp+/hbQ0LI88n8IPLQWvs=,tag:H75h5047Upa/DWBhr5Rugw==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZFRpZWpFMlhEcnhtZFY5
            YUxTVVdsWUpiS0JRSjZLQ3hqcDYvYmdTSkRFCk5DOTl4OFlhTi9QRDFaa2RpYnVZ
            SjBLTXFOMTFmSERqWWtubDdqd2NzME0KLS0tIEl4M3g0Nysyb2NUTTJCUFNRMCs4
            OXRHVzhNd3daSjdNeDErT2NlZHpzV2sK8WeWCYcvxXGiLJ3Rme4astxeBWYqOZ1i
            zgOwUitsAPer1ZtCeTlb4cOU3Lj4HEGeHXdjECCr4L5RHn6IiYpEYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T22:17:05Z"
    mac: ENC[AES256_GCM,data:KhHNHObvASx+C3XVJQgvjCiVjOcfQ8mWHlTyU0qf0J3vsZofwrVMTGQxd/WXN0A7cyO4tatlgHyxSkHvEtQvjxfCwXDO3dN2h25HMuvcEhBB07ke4dPfC/MqZ7Ezwkvh2cFuLLMC+szWFQemKqkZOuxcgArWf4wkQu6W+0reh+I=,iv:Qw7+2f6+NpYIbptmAuqUwGrKDF/Ii2tbvOV0Nhcwzws=,tag:SdAN2Y3iCumlqg6LzEA7Ug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
