auth:
    admin:
        username: ENC[AES256_GCM,data:x0GdswgkuQ==,iv:bfQw4Zb9iTGLXik6pV5t1xhJqzaxR6eiaToQS8t7m+o=,tag:0F1ku4uK+13EFCYY9/rh+g==,type:str]
        password: ENC[AES256_GCM,data:M1nbtVWJCzn0sAvb,iv:3fk0E9L416caZmt37AF64XUq/GcQy4V0nTjJhB+g0io=,tag:ZytJrT8utFLnUGG18+pGuQ==,type:str]
        token: ENC[AES256_GCM,data:0CJn1Zn5mEodWq1zU/Ka9uBgWEY=,iv:b8FZSJV/ugvtnTjLxN89Lk917Xd0y0TxKp/qFE1MBFM=,tag:QT8UvSfqEE6jTf4OsI9Cjg==,type:str]
        org: ENC[AES256_GCM,data:lkwkfQ==,iv:LwHQaF8pK7xto814UyaKRIbzpl1vw3J5CzLfE13Q21s=,tag:9gTS+zUDg4xmCNcsdrwAhw==,type:str]
        bucket: ENC[AES256_GCM,data:U06Q7g==,iv:ucv39nkBg4az2Bc2h72U0R5r1iKLEWMPN9KT4GVnTAk=,tag:0AuvDYdk4H9Pbhro3zymQw==,type:str]
        retention: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTXQrS0sxQVdGRklmWklu
            Z0JOVEhiMit2M2hSVXJBR2svQmRzKzdqc3hRCncrSVJVS2YwRWpBc2NHeWZKdWFx
            YnBkOWxWYzdWVzNBOVNlMk0zNTlYU28KLS0tIFQzd1NETitqbVkwaXZrd1NpNXEx
            NG9ObVk1eXovTVpvV0VhU1N2aUM3QnMKsyXFdyKHz4tjpMCO8obXpz/ij2k8AhfX
            LhL5UCYGI0mBCwXAPIr7nBzvv4PEryDtrB60upWykrslSUigPd7d6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T03:33:25Z"
    mac: ENC[AES256_GCM,data:dC/XfvKuGi4d1NW2hBB6oTLfkFtCU12KDVXszEyigQQ4urD/1jGaeKfLbZq+yj2JOdM+EfuM/16RvMlFsMlCQ12fawYJQd/F/oF4W+a4ejeeDJpeHPb23d7+IfH4uMiV8cujkriGE3PEwiFD0JvrkQ4a5pgsNraj6gbHayJJrx4=,iv:aK4YFkp4KQJx8cSgaxlq58HmFDlgaI4F4eRIa41atvY=,tag:VF30x177eiY7oZS1LwYVHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
