secrets:
    db-secret:
        enabled: ENC[AES256_GCM,data:Ei3ZDg==,iv:RoAvcVyjYdSt7WHmT4KfNCV70WHmsloVMVm2CfnYxdA=,tag:ZhBVyqYTnW96nES8X0Bq+g==,type:bool]
        forceRename: ENC[AES256_GCM,data:06wCVQbvwBsghyOwdHMzKw==,iv:cmRG3ozS9PeD08ONSvGN51xuXGOOUfe8VW395f6fkcY=,tag:nuwdwOx5EcqcP/wnuJWu6Q==,type:str]
        stringData:
            password: ENC[AES256_GCM,data:FC9vxlLi9042dEWjFtjrgRsOQuw=,iv:9ECMQ5Xf0sQlY/snh/HaRZ1EKWLjXNUubea4CUvrirA=,tag:eSXRqf9rvUcjty4ANNCKxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFak8yd1hXZTN5MnV4OWx1
            OGJHRUd3QWdicVBTN1lDaTVmVUtNRmVubkZrCmhWcWdaeDN5VkNuc3ZWRVQ4SDh0
            MFZQSFo1U0doelVPUjVrSzFpbHhLemcKLS0tIFN1ekdwcFRwcXY3TG5pVjA2M3Bi
            eVF2UzhwRHV4YlRBaWtUdTJaNkc0MUEKG7o3U10smq6ohRsHekJ7gdPTDf4I05y1
            aTPTkNKFSu2QwOofsttyrpX63VnQQMaw90frVIKUYqG5Ipgez9njwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
    lastmodified: "2026-07-25T07:38:55Z"
    mac: ENC[AES256_GCM,data:00TlsH6wfOnwpYdOG+9JDeFD/2WncZ3tObAXgvuewPVIsrZnstg0GIeMopemVlCsZV1mQPw6/Os9jnaT942wuKKkuBT12tjRGOdqnqdq+qs5ZfMLP9ydA5DnaT7mhXvBQ6IZygwoXJk+ng4IvifJQoys00w+LrnPT6sphQ3QT+c=,iv:k1JFoGuV9MljfFEdeIkxeVI6jj/JUqNo5zsqiSBDpdA=,tag:dfiPbubB5yQqJzG2+BVlxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
