# templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
spec:
  commonName: "{{ .Values.certificate.commonName }}"
  dnsNames:
    - "{{ trimPrefix "*." .Values.certificate.commonName }}"
    - "{{ .Values.certificate.commonName }}"
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Release.Name }}-cluster-issuer
  secretName: {{ .Release.Name }}-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "{{ .Values.certificate.reflector.enabled }}"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{ join "," .Values.certificate.reflector.allowedNamespaces }}"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "{{ .Values.certificate.reflector.enabled }}"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{ join "," .Values.certificate.reflector.autoNamespaces }}"