
resources:
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: victoriametrics-ingress
      namespace: monitoring
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`victoriametrics.local`)
          kind: Rule
          services:
            - name: victoriametrics
              port: 8428
      tls:
        secretName: certificate-tls
