# --- vmsingle (The Database) ---
vmsingle:
  spec:
    storage:
      volumeClaimTemplate:
        metadata:
          labels:
            recurring-job-group.longhorn.io/default: disabled
    volumes:
      - name: vmbackup-nfs
        persistentVolumeClaim:
          claimName: vmbackup-pvc
    vmBackup:
      destination: "fs:///backup/victoriametrics"
      volumeMounts:
        - name: vmbackup-nfs
          mountPath: /backup
    retentionPeriod: "7d"
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        memory: "1536Mi"

# --- Scrapers Configuration ---
kubelet:
  enabled: true
  vmScrapes:
    # -- Enable scraping /metrics/cadvisor from kubelet's service
    cadvisor:
      enabled: true
      spec:
#        scheme: "https"
#        tlsConfig:
#          insecureSkipVerify: true
#          caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
#        bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
#        relabelConfigs:
#          - action: labelmap
#            regex: __meta_kubernetes_node_label_(.+)
#          - targetLabel: __address__
#            replacement: kubernetes.default.svc:443
#          - sourceLabels: [ __meta_kubernetes_node_name ]
#            regex: (.+)
#            targetLabel: __metrics_path__
#            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
#        path: /metrics/cadvisor
#        scrapeTimeout: 30s
#        honorLabels: true
#        scheme: https
#        tlsConfig:
#          insecureSkipVerify: true
#          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#        bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        metricRelabelConfigs:
          - action: labeldrop
            regex: (uid)
          - action: labeldrop
            regex: (id|name)
          - action: labeldrop
            regex: (feature_node_kubernetes_io.*)
          - action: drop
            source_labels: [ __name__ ]
            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
    # -- Enable scraping /metrics/probes from kubelet's service
    probes:
      enabled: true
      spec:
        path: /metrics/probes
    # -- Enabled scraping /metrics/resource from kubelet's service
    resources:
      enabled: true
      spec:
        path: /metrics/resource
    kubelet:
      spec:
        metricRelabelConfigs:
          - action: labeldrop
            regex: (feature_node_kubernetes_io.*)

kubeProxy:
  enabled: true

kubeControllerManager:
  enabled: true

kubeEtcd:
  enabled: true

kubeScheduler:
  enabled: true

kubeStateMetrics:
  enabled: true

# --- Rules Configuration ---
defaultRules:
  create: true
  rules:
    etcd:
      enabled: true
    general:
      enabled: true
    k8s:
      enabled: true
    kubeApiserver:
      enabled: true
    kubeApiserverAvailability:
      enabled: true
    kubeApiserverSlos:
      enabled: true
    kubelet:
      enabled: true
    kubeProxy:
      enabled: true
    kubePrometheusGeneral:
      enabled: true
    kubePrometheusNodeRecording:
      enabled: true
    kubernetesAbsent:
      enabled: true
    kubernetesApps:
      enabled: true
    kubernetesResources:
      enabled: true
    kubernetesStorage:
      enabled: true
    kubernetesSystem:
      enabled: true
    network:
      enabled: true
    node:
      enabled: true
    vmagent:
      enabled: true
    vmsingle:
      enabled: true
    vm-health:
      enabled: true

grafana:
  enabled: true
  deploymentStrategy:
    type: Recreate
  plugins:
    - victoriametrics-metrics-datasource
    - victoriametrics-logs-datasource
  grafana.ini:
    plugins:
      allow_loading_unsigned_plugins: victoriametrics-metrics-datasource,victoriametrics-logs-datasource

  persistence:
    enabled: true
    size: 5Gi

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"


# --- vmagent (The Scraper) ---
vmagent:
  spec:
#    extraArgs:
#      # Enables detailed logging for scrape configuration and relabeling
#      promscrape.config.debug: "true"
#      promscrape.dropOriginalLabels: "false"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        memory: "1024Mi"

#defaultScrapeService:
#  namespace: monitoring

victoria-metrics-operator:
  admissionWebhooks:
    certManager:
      enabled: true
      issuerName: letsencrypt-stg
      issuerKind: ClusterIssuer
