your:
    secret: ENC[AES256_GCM,data:g02axw==,iv:OkKGzWTAG+/AJqwIb+6ja+dGqndfqvXG1QCwqeAKiz0=,tag:0Gc4KKfVo1dSqYr9ezCgzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTEdDcHJMa05mVlFkU2d2
            bVlaWEhoZHJ4TGZJTnBPb3k2czlKV2lhVVRjCmxTbkxoRHlrQmw5MGtsMnRSQVYr
            WmRUQWs3ZlA2ZTdsVkV3NUFVVkRhNk0KLS0tICtyNW1LT0xsZHRQeTBPa0E2c1lN
            MTNuemVKQ3Jscm5NSG4xUzkwdUpUT3cKeTD+G3ijj0zDzim5Y23YaORvgypbEPfJ
            hSaJpOwCgYF5LsI5NEE/Zg1/poLiKlD1w+P/iuSKIpVsfZH3tpBlLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T12:46:06Z"
    mac: ENC[AES256_GCM,data:3HIEIFNnP9y1tnQnKE2ggyD0fRYsmsg2YxW9EebfQ5aluV3vu/hTedXVvfvjd2FbW88H39GYWTpt4+FTaK0W8nTa2ygfvRabQnwwMBQuauefZpysduHLs8p36zr5NuNnW+ACHgIBWkLW7VxfKnBqVQgRJqzvgmiCWtsG5eLlnHA=,iv:qQz234KIhaMyRJAH1gTDMctXaD65f77aoAU9Cp41Ftg=,tag:/aISoo+x6zvqkdYA1WBxXQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
