image:
  repository: ghcr.io/nilson-aguiar/manga-fetcher
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  storageClaimName: standard
  subPath: media

shm:
  enabled: true
  sizeLimit: 512Mi

resources:
  requests:
    cpu: 100m
    memory: 2Gi
  limits:
    memory: 2Gi

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - manga-fetcher
        topologyKey: "kubernetes.io/hostname"

tolerations: []
nodeSelector: {}

configs:
  schedule: "0 0 * * 0"
  activeDeadlineSeconds: 1800
  backoffLimit: 1
  terminationGracePeriodSeconds: 60
  values: {}
