#ENC[AES256_GCM,data:VB224/dMYTOZnYtynMfXxdfKe0eazMSuvEJS431VeVkMRQ1jj+IGEuYdtEM0snZue8M=,iv:qM7QqDmpd9JtYfPtSgbw+sgatg2pyelbbUZcipKQCJA=,tag:KhGKgcHCbwk32AI8+wwvOQ==,type:comment]
#ENC[AES256_GCM,data:eytKnC09L8VMbehW0Km1vZTWmEcEnxdSMevAlhs/nIUes57VvrAr1IVIqfTrML1k+Wcuqz5spGk=,iv:wPu7kzZmU3ACkZMl2FBr6VcfBOPVsnNSt68z/2XkOqY=,tag:Wi7kbjGaNUwI24dIX8EfcA==,type:comment]
secrets:
    actual-secret:
        enabled: ENC[AES256_GCM,data:niZVMw==,iv:uvBtgYRyCkjtnG7fCGw3k8+FYBZ/yiafLAmmauao6zQ=,tag:m3yD++M6Mikii6h/soSWNA==,type:bool]
        stringData: null
#ENC[AES256_GCM,data:h1qoYYlkRgNDRKO30pfnAWuIcMZTM+ASjlJVx2RIdfX+43XX8kTm,iv:bow5q34EJZVVXMrzNYTRpTF3wCEhwDB7OogfLfsxiN0=,tag:p8oqqPi7ftMKKSVKZF+eMw==,type:comment]
#ENC[AES256_GCM,data:Nf3z6r8bNvrJ0+/8oqd7nG5sO4pzCpebqKHnu+rXo631UGJQflh0DvawFAU=,iv:YV9Tt8eA1PDv2ti/zBLMqcpGKmOltQRJtt0CUuP401Y=,tag:IPbEhsne9PpPlp4lW4cKrA==,type:comment]
#ENC[AES256_GCM,data:GuQGbUdBuDa+rpXKCdsP74k9D4O8ukjhnF1RD1qfg+RFVNlRKQTas9xUOTtH,iv:ESacABy7Uump01dql6lfguNZ+mfg1rO6ly8cAPZq34w=,tag:U5aBjV8z5TWEzG49RwuUNA==,type:comment]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VjJNelQ2WTJpOFI5dllm
            bmxVeHhWcVVaQndlaVowY0d1aFhrYWJ5cXlVCjR0NDVINGViZWxqWkFMaTh0dHpD
            cVptZHJrR3ZQTTVSM053ME1iYjdmMXMKLS0tIEpNSzRaLzZYbitoblJKSzNWbTVo
            aEJYNG1SY3ZjY3NwYnpXRWdaQmtMV1kKNxQMDSyPvkwvZyyCx+oLrE1U9JBnDu6x
            NGOmaJmxs09Mu0s6rk6LuNooyInAQZUDqztkec2O2XZJVxY2VX7Caw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T14:07:16Z"
    mac: ENC[AES256_GCM,data:ALP535Li1wJ3GdX2/eEs2dAO7Nf4pvFFSezpN+4SxXC0D5dHrE7zDAhx1z5AYJ640D4vKwFJvCN9K/+K+F7t0+q+Ge6aE0uIUZOLfFGR1/K4MEwjU2CFfOraw3m3SBFhRbD4nvJRQqWFX7hqsRfCePezO5PJ5wVxLipbe+L8oZU=,iv:TEhJur/TsIb5Tu/TRVbfJD4BYVeDGzEi/UlC3G4ZrAs=,tag:OgJazq53beb1VCOcJfdfAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
