#ENC[AES256_GCM,data:4UziZ+ZU/zlB3pWsnc2u5ErVovFyzcfthYemGt2Xci3Cku8FsJAbnuNS3m0bf13a2kg=,iv:S9oN/KgQ6Py6EeS53gJEiZImxYFo+yX9Nbc9a19v3Yg=,tag:yJvrBqsD5jXrJOV7YpGKpg==,type:comment]
#ENC[AES256_GCM,data:peOCdo/tnHeyw9Hq2U+l9lk9r0rnxZutlJWapilxCGebiWYJ61c2akYhYc0R6hWcuOK6PXPGfdk=,iv:H3/0pF/+a1T23QHV3FYhVNKKuhnDQGU0q27bme2T/vM=,tag:rfbug6XU9+utmaH3GG7nPQ==,type:comment]
secrets:
    actual-secret:
        enabled: ENC[AES256_GCM,data:0eBUHA==,iv:6gxxkSqvel3biS6cHCrLdprmo7ifX1pBeaIfbMFfFgQ=,tag:OF94jRbds6+DCcOR97ZRyw==,type:bool]
        stringData:
            ACTUAL_DUMMY: ENC[AES256_GCM,data:NemNu0ZKIcSRls0=,iv:3qQx2VrDQ0ySF3zfo05oIqguEG+DWCeni4cZsBFbiPk=,tag:C+r8dkMjO1h25f3mNf2u7A==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR2Q3VTdDeXhsdU1zYk5j
            VkdZcFRwUXZFbGkxOWpZQzVFY0NQclFSN0RJCnZRVW9EVkRBY2R5WnJyZWlnWmdt
            K29FQW51R3Vnb05PcFQ2MHp5VEIxdXMKLS0tIHMvTUhoSHQxWE1GdE5Dbzk4T0Zr
            eTRQbmhIcHlPL1Jja3RhUjE5VjNtSVUK+Z0L08ExllI1iIxeejXaCSWs2AMRLeYh
            lwEJy+uWCOIhXPi63Fa0TBkgkBnX7NUhri4hebyik8ZWDa9FSrueZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T14:09:36Z"
    mac: ENC[AES256_GCM,data:LxaTjymPvTE07OkfM9LEB6VQTQpNNN/DNb4OWJRAKe1Ewl8Vfn3ERKdwh26GAcgdj2KrIVIeqPv/RmlZN3LvxKz+Ve7O3FJIpy2xC69cOicgctfBLW3LB+hJHF2BRprU0Lq1velWYgzECCgy+mWDkOCyZzWG5/iINjQdGTJux/U=,iv:L0NmvX4x8JgmKJmaG3fnVrs1tcG3WVPgsiTvbIr01DQ=,tag:sQPzfHBuPu/qurJGPM6mcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
