---
#repositories:
# Add your private chart repository if you're hosting the chart
# - name: private
#   url: https://your-chart-repo.example.com

---
releases:
  - name: tinfoil-hat
    namespace: tinfoil-hat
    chart: ./charts/tinfoil-hat  # Path to your local chart
    version: 0.1.0
    values:
      - values.yaml  # Default values from chart
    secrets:
      - secrets/tinfoil-hat-secrets.yaml  # Optional: for sensitive data
