repositories:
  - name: bjw-s
    oci: true
    url: ghcr.io/bjw-s/helm

---
templates:
  bjw: &bjw
    namespace: tinfoil-hat
    chart: bjw-s/app-template
    version: 3.5.1

releases:
  - name: gluetun-vpn
    <<: *bjw
    values:
      - ./values/gluetun-vpn.values.yaml
    secrets:
      - ./secrets/gluetun-vpn.secrets.yaml

  - name: tinfoil-hat
    namespace: tinfoil-hat
    chart: ./charts/tinfoil-hat  # Path to your local chart
    version: 0.1.0
    values:
      - values.yaml  # Default values from chart
    secrets:
      - secrets/tinfoil-hat-secrets.yaml  # Optional: for sensitive data
