qbittorrent:
  enabled: true
  image:
    repository: linuxserver/qbittorrent
    tag: 5.2.3

  persistence:
    config:
      storageClassName: "longhorn"

  config:
    timezone: Europe/Amsterdam


#  kubernetes.io/ingress.class: traefik-external

service:
  type: LoadBalancer
  annotations:
    metallb.io/loadBalancerIPs: "192.168.1.205"

image:
  repository: a1ex4/ownfoil
  tag: 2.3.0

persistence:
  enabled: true
  storageClassName: secondary
  accessMode: ReadWriteMany
  size: 100Gi

ownfoil:
  gamesDir: "/games"
  dataDir: "/games/.ownfoil"

# values override
ingressRoute:
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.1.200
    kubernetes.io/ingress.class: traefik-external
  enabled: true
  hostSuffix: local.naguiar.dev
  entryPoints:
    - web
    - websecure
  tls:
    enabled: true
    secretName: certificate-tls
