encryptionKey: ENC[AES256_GCM,data:eOTauJFtW6+1GlgD6zMjbX16YWA=,iv:2y2S5mrpFvXPSVCI8432kdcISsIRQLyJ3xdILnO1Xi4=,tag:aHbYVX+r43vZI6AL5uJzqg==,type:str]
externalPostgresql:
    username: ENC[AES256_GCM,data:GJIM,iv:rrS8WM40NFFGGmmSIf1yaNabMntMbbN7AdxURw7V1V4=,tag:IX4PMbB55V0moQzF6zfBuA==,type:str]
    password: ENC[AES256_GCM,data:EBLupoSIOzfxQeHE00TQwzHeomA=,iv:yzuoFwqxw5/Gn2d91TYqhgbXS32Ib2fOyQFAampXVeA=,tag:EBz81tgqNPF/tfWzt5uizQ==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU2JiZ2NRVUtwekdZZU5D
            YzJ2QzE3Si80NXU1Witvc0JWVEI0MStBeDAwCjdKTE5pUmlIMGwxWVpBOGZXcWxy
            c2pUSUUxK242WXQyMWNOdjk4QkJEMWMKLS0tIEoxZGFQcjY4T3ZwRUxIVml5M0tm
            Q1NUTVVoeWlXemNvVXdza0lEVHRYakEKwok+KPjsikNeclXYvDP1dNA3nOUg42af
            1zpORWnoki/WntuPhQ7fKW4SntjbIz1+akVj8Yxs9OOrINbzc1YikA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T07:24:39Z"
    mac: ENC[AES256_GCM,data:bQSR3hMGqDKbrAEiMa2Mtl0wvobK0OXvNkc1QkjoFTSbFodcPhPIARe3PgPvIfEzU7mVAHE6tIcEiX7zyoooJ+LldbTPlDVdM0QASvW6hrBSLrvMUYQpzdedAflT0ctUULUSpivmPZapFjmvHd2myxOb7wmmIUKNqat8/CI54fw=,iv:FZ2G52K5jHXz+8jRO96XBpUW30UTGmppGTzDei6XPcQ=,tag:Khwx6mYrSEtGyM+xfJblnQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
