apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager-ingress.yaml
  - grafana-ingress.yaml
  - vm-ingress.yaml
  - vmagent-ingress.yaml
  - vmsingle-ingress.yaml
  - vmbackup-pvc.yaml

configMapGenerator:
  - name: grafana-dashboard-resource-waste
    namespace: monitoring
    files:
      - ../dashboards/resource-waste.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-argocd
    namespace: monitoring
    files:
      - ../dashboards/argocd.json
    options:
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-nodes-copy
    namespace: monitoring
    files:
      - ../dashboards/nodes-copy.json
    options:
      labels:
        grafana_dashboard: "1"