apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmbackup-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: backup
  resources:
    requests:
      storage: 100Gi
