secrets:
    secret:
        enabled: ENC[AES256_GCM,data:HOB2qw==,iv:LiFITHOBwqtdgWheEzWawuG0y53G1tIJLcTAK91eaPg=,tag:JDMypwnGWedk94/kQSMrcg==,type:bool]
        stringData:
            LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:SWErSTEIomSC8WrQ3eHcK68z/xMXCAjSKWzKSIMEQT8=,iv:1ddoig9V+tJTsj3eRVBtzJjBh5oz4kZuV5ZZHU1xWfc=,tag:m08yo4Bfh0dCUmH+CZCyRQ==,type:str]
            LIDARR__POSTGRES__USER: ENC[AES256_GCM,data:By+yOzjq,iv:3Q6NiePRsO7Qy6KIVz/lKM1ZP+cMC92XgtEmSJfVbnY=,tag:w7i0C4O4SNd+1y9fmeCYkw==,type:str]
            LIDARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:9UXo3tvfeclUPqlfGqQtIdI4zQ==,iv:9TCjN/YLe20MBaQzqEIctaQI6KuUDRJnl5GI4XpXiPE=,tag:tMkjMbhPqJp5Bio7sFz7yw==,type:str]
            LIDARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:ic0BXZsL,iv:R4qLHtHV9gIVzdHY9Sbb4lwMWkdNVvDaJEUxaAdej8E=,tag:5m3JGmPSTERP6rxpBbGiHQ==,type:str]
    init:
        enabled: ENC[AES256_GCM,data:cn3efA==,iv:eBsAZqOzbc2JlNzTn9qPNsFD6Yl1MwZtjaotbF4xlSc=,tag:EJlfhZbn7FP22JosD5uK+w==,type:bool]
        stringData:
            INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:z1+nqkFe,iv:4kjx9za6fPMziEz7Zib+hlqCzBuPavJiP7okXzlKaKs=,tag:HsZtyM79k5w5tJ7yZ94Zdw==,type:str]
            INIT_POSTGRES_USER: ENC[AES256_GCM,data:MwhL1XMG,iv:cKm10BS6ZI+2T7loYjqOYCqeGpE6Bso1RdUeaZnlma0=,tag:KjYKxnFAE6fZ7hX0fcP/lg==,type:str]
            INIT_POSTGRES_PASS: ENC[AES256_GCM,data:D0z4czmh9cT4lmBwF4wZX7n9ow==,iv:QIkpBxqv6CgBhGV27IY3jbvzQJiJTqPuLao/LfnqA7k=,tag:n8JVhos7eULx4e+mHzTL5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QVNSZk83WDYxTm5kSHU1
            V0c1L1dJVmFPSFZGbGVMS05wSGpPeEplWkd3ClBnaGFYenVyTG1naDNuWk1VQ2xZ
            em41WTgwNlJnVEs0RTE2R1NPNzUrV00KLS0tIGExRWpvOFdOcEg3cytZSk5SVWZs
            M0d2cWttM0daOHpWaklXQ3p0K2tGRWMKtw5PkwWr5flfZKI2awhk7ITQquyaD8hp
            Lz3pUhI5fN3WHgVz1CPCFaXUPYOuAmnxdFuhEMbueRJLLTMzxuYKEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
    lastmodified: "2026-07-25T04:50:13Z"
    mac: ENC[AES256_GCM,data:XAgFsZyR9DiSpqmDzpQ/MPDoBx3D7u3CaZFOwKLk28e+JhFYui+yi6WCu8fiJmd36q2+i2J/ESPb4V8SBFKB7o4Aqaq+JDffNZHe8TnCBj0Z4Qu3x+M3hiGmFLC5uFBIOGxg+WpsjXKHu7dDEHA158qa4qcl6a2DOpck65/tSaU=,iv:KlXuNtwCmKA81CA+dyC+SvL4Qq3crOKAq3O1k1dZL3U=,tag:Mjvp9WmSVFo3zIQJ+PGm8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
