---
# yaml-language-server: $schema=https://artifacthub.io/api/v1/packages/d5dad873-8e69-411b-8391-933d4391988a/25.29.0/values-schema
rbac:
  create: true


global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

server:
  service:
    enabled: true
  ingress:
    enabled: false

  ## Prometheus data retention period (default if not specified is 15 days)
  ##
  retention: "5d"

  ## Prometheus' data retention size. Supported units: B, KB, MB, GB, TB, PB, EB.
  ##
  retentionSize: ""

  persistentVolume:
    enabled: true
    # accessModes:
      # - ReadWriteMany

alertmanager:
  ingress:
    enabled: false

prometheus-node-exporter:
  enabled: true

serverFiles:
  alerting_rules.yml:
    groups:
      - name: dockerhub
        rules:
          - alert: DockerhubRateLimitRisk
            annotations:
              summary: Kubernetes cluster Dockerhub rate limit risk
            expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
            labels:
              severity: critical
      - name: oom
        rules:
          - alert: OomKilled
            annotations:
              summary: Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
            expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
            labels:
              severity: critical
