## Common Labels
# commonLabels -- Common Labels are added to each kubernetes resource manifest.
commonLabels: {}

## Overwrite Labels
# overwriteLabels -- Overwrites default labels, but not resource specific labels and common labels
overwriteLabels: {}

## Define Pure kubernetes resources
# resources -- Define resources to be deployed by the raw chart
resources:
  - apiVersion: "k8s.cni.cncf.io/v1"
    kind: NetworkAttachmentDefinition
    metadata:
      name: lan-bridge
    spec:
      config: '{
          "cniVersion": "0.3.1",
          "name": "lan-bridge",
          "type": "macvlan",
          "master": "enp2s0",
          "mode": "bridge",
          "ipam": {
            "type": "whereabouts",
            "range": "192.168.1.128/26",
            "node_slice_size": "/28"
          }
        }'
# templates -- Define templates which will be executed using the `tpl` function
templates: []


