secrets:
    app-secret:
        enabled: ENC[AES256_GCM,data:eNrAsQ==,iv:FBcZMCSM9+e1F+HKxwZYzw1F582oW4mLLdzFJNB5WYM=,tag:2wkIZs4FtF4qSmy0S84jiQ==,type:bool]
        forceRename: ENC[AES256_GCM,data:NK9LTZnI+xLEdqRE1vZ3nbhx,iv:2fc7InmLY6lV0xLx/HtWNQysHVE+1WcH1/KRZhBrJMI=,tag:/6PfTjvNeZwYO2NcmXOypg==,type:str]
        stringData:
            adminToken: ENC[AES256_GCM,data:i/yFh3/wLqW2f/1LHFVgNW8UyFOuZKMy9pmmexbPCBXWFXIiI+Z7/PkURT3ysz4MkDKso+50MLLYBVy9gJXZpoLbea2yeo2tmANT+xxl8xy8+iG/a/bnbgWW1IBW3uHsY1kdZxVzkd4gBUsc51T9FBPbvoQvsQ==,iv:U07S994GqvhsNwwb0Y0loaxlewCIIs4CTrMsAKZUHUw=,tag:B4Z+9m8O1Ktqi0fciHtQ7w==,type:str]
            dbPassword: ENC[AES256_GCM,data:Yw3d97KUCX9JN64vQLliDYOHNcyprWJdzr9/6BNPKUY=,iv:0kiOd9VNyyvanyvzTczHnRXFkmQnDsYgCXsoURTikm0=,tag:KVJLY4NWPkT51qGZ2U8efA==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:CtHK2rD5uafTvNVDvYBE0U9ERr1pvmNXtUWsDtXDR6j6FlnntJafLLk+JXB6CawPj7PFcPP4odwVvxPy1ManS9FXFiEGvEQI9lUxsfyGCGJpFkOIYfY8XLxiDyyCacUPPI9umaQE5d6mbI44Us2e/Ovf7yub,iv:TL/szt6ZE4WzAERkm1RllKU4KxyaQ+PDe8CMENqG6pU=,tag:+cuyyZa32vxe1TwOlDgm4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdHFCSWhBK2VWb1QzTngv
            VXd3QUxuUHdRT2R5ZWRib3RqaXAzWnhiN1IwCnZLNGsvNFN2NXlPaER3bWxqUDQr
            d0tzaHh1Q2g5S2JwN1BZZUYwNThMenMKLS0tIFd1dU1ua05yZWtDSGNFQjJhY0ZO
            SDR3Y1VQMnR3VXRUTWJaTlNxSllvSk0KWjI6ZUzOlLw7dQe20+h2UzjGhmjjRLKZ
            /bVko1doFon33Wgep49iV8XYs7HILPXuHVyYc0QQQGKbnsR00zTEeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
    lastmodified: "2026-08-26T05:54:59Z"
    mac: ENC[AES256_GCM,data:3lKpsEh8lmPdrnmiK2uqX5xQrILnYjnyfttyiPu8xNUAWBctk+h3iVQ32Km0wLmaWIW48lHVAhMFyGvjEUFWmXJDQk03E9f3VZBfW2EjuvZcTpAUfJCgmxpLMZAcswrwKCDZVSfEEBDv/f6ssE+rPNU6EIMjAuDhxiHlBVlbQEI=,iv:kYRI3VCLYOEfuN8/GVXv1cDQdngmXKnrj7JcL1CLFy0=,tag:5A3beIht+JXZ81UbONxPgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
