rawResources:
    vaultwarden-secret:
        enabled: ENC[AES256_GCM,data:Met/mQ==,iv:DL+n706ByApCvzOnWXM4pWfOq5lkOXO7DcsLxZa2ANw=,tag:w44ywSklg0ZcXfRhpSFPpA==,type:bool]
        apiVersion: ENC[AES256_GCM,data:WrI=,iv:0O1Bj44CtjbrvxY9m+0ZOFtZvdXr6nXzA0m522R2tfw=,tag:zjBcN/ALDboPlbTL4knkgA==,type:str]
        kind: ENC[AES256_GCM,data:OvnzGaqY,iv:EOKVrIzJSSavV7iCieJU8aOdtbu3LtRfhAwgxtQtmrM=,tag:Mrne7kge+0m12aGKp7Ieew==,type:str]
        forceRename: ENC[AES256_GCM,data:qDBkWM4lWR1pOfHc6P0Tj+0G,iv:foG8AlqTvSA4AY9/oDxdm5p8wsA8cP+XqGQhalQh/3Y=,tag:ZeAbGfUgLbRX00F7Ot5M8g==,type:str]
        spec:
            stringData:
                adminToken: ENC[AES256_GCM,data:7/rj/Otp2beI3ONzTj5JG3KCeQvQpv0Giet59KhSFqrC58/HfkyCpQqLOykX9jxkF7BrS4U6xRYqdvVo1qxUvc3ScG0gghh0KArXcIlxmdxrJvhstgkHKjVA0kuwIPtyAQn3u2DPS8YCDLyQ50IAHseCAu5zwg==,iv:4Wmn3Bmm/+BjwjQ5ZA3bWIlJX66nE+t2C9SfHT1pNpE=,tag:+gA6hMPjAb/6FUYMDFYKBw==,type:str]
                dbPassword: ENC[AES256_GCM,data:jh1vTBkr5yjPyNHJBIGmIzVKj/nSep8DxPDf9rOE5F4=,iv:OCQwYpqVYLF1kTLReu9izsnaAPXrVGzLR6MvSfT8u3g=,tag:e+BaV+AFMFOmoJZZ9pgt9Q==,type:str]
                DATABASE_URL: ENC[AES256_GCM,data:ZO5hrPw8BfSI/fB3YjIOPFDh7Py+65pxbPhf4VTT24Knoig8347WPS61xe1jN/mtPibBLvTIeH+xyUsgnPdFoNNWQ5F7JErXw/x2DSPFkylqLi1p89dc60n0A6RWgaAFx5jZnQJblhldSnbqWqCiuW0hkKKj,iv:z2xnMZqq78FJNN11erPEz0glE8xVZ1IccpQdxztwNpY=,tag:vzop9uRqet/1eX5yFMUJng==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSnM0b1hyU1I3RkhNK3pn
            KzVUSk16STh5VmFCZE41bks4a2Zaa1RIOWxZCkt3VnhHV1B6c0tHb2o4YXRSRjRl
            cXNsaWxuRzRDRE1oSlo4UUJtY1VvbEkKLS0tIDBPTEZ4N29tSklQd0JreUVQekds
            TGNkVnN2d2EyS21ydDd0RGFlaGFtb0EK8p5326FRfE5agtEE65h1xULMC4fo7Rlc
            wwW5hKeuI3qfPWhRwmlPaOI6+UjN4uP71y1Mx2dg3gRVF9IUnBRcJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T20:47:39Z"
    mac: ENC[AES256_GCM,data:dLxBE5hcNvTuIbSjhYEGB6rc8rrO+h71y8ckainUuSA/WTLxIEKtIRT7rV0IG0/b6yLjHFVcU4+kUbiJEewUYAL163p6RKQ0oqv+DMakQJh+8iCjumX5Tg2x1v/2TAS2EtNuzzb4kW794HPrafg/kvMLw5mpeSZZYtxdKfoZ+fA=,iv:crhVYX7HhgHRyIGl+7KMSbIYVIrQcpFPtlVOaBjnixw=,tag:emDjeoJHiqfgIv/qR3uWAg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
