repositories:
  - name: cloudflare
    url: https://community-charts.github.io/helm-charts


---
releases:
  - name: cloudflared
    chart: cloudflare/cloudflared
    version: 2.1.2
    namespace: cloudflare
    values:
      - ./values/cloudflare.values.yaml
    secrets:
      - ./secrets/cloudflare.secret.yaml