telegram:
    bot:
        naguiarStgBot:
            token: ENC[AES256_GCM,data:3EzNw9L2MrPtrY/Jagp75Uoyf03yzU1xq0yv318iqCWnMAc/H9Q60J7FLlQFeg==,iv:U8Eett5iw9WsVv8JzWbEorWPl6xpAHl/pPu1oBKt4ew=,tag:W2Mvdppe/h8x+Ql9PaKutA==,type:str]
        naguiarBot:
            token: ENC[AES256_GCM,data:Z4s42RRh0YpxCSBIctENoFv3c4UMUlvVIk0gQ09FewaiG3a0/Cr6RNUW3+xETQ==,iv:vFl8sUsQNhViZWO8ilZOniLUmE1NDIL5s21N1B99Nqk=,tag:1SQBdUaUKnLoD7KGKeNgjQ==,type:str]
sops:
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNGNpRHBZaWlrU0lHYk5I
            eDRnalJGUTJkZmR6SS9lYW1NenBJSkhVdVZnCkFoS3h5YytWUFpSaGRtY0lIbGhM
            RFFSd3JlWFBCMk0wZnltYlgxdXJwaGcKLS0tIGM2TjhBYlR3Mnc2R1JTVlV0K2Fa
            K29WUFZFOGxST0ZxaDRrYmNXOWh0ZGsKmrmv886DoxoEMp7LJs0PwyH5S0XEoNnb
            ocY/DusHRQn25k6hbAztcS4C5orw2YvY2Yx1Pp4eRh/VE4xvlPHbog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T07:15:10Z"
    mac: ENC[AES256_GCM,data:fMEGc9oOE9TMJXYLcYtDvvq6JGGfXFaIb5uCHA9elQWkKegcMS/YQBzudPcq/uqybeZyCXu0CH+mscJupWKOP8sW7qWHhxlkqmhnhVZ5gW1yuiwg/FUZmawdGDMqjp9ADxWgsC976dYLeDWzZ+yjTB35un3Gwsgmg36kNI2aEk4=,iv:rc9cRFm5ShpwRQ2TfjJt+xWzV7H3l1NShnwjjo1jCQI=,tag:gyiOkl6PMo4nSejDWI+4UA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
