cloudflared:
    tunnel: ENC[AES256_GCM,data:OGzNKhsfL1csUJgLKNV4FCXf2GWi9hXJZnzWpbLCx1YBGt7+,iv:N/brEsiJ47EPz6DmtTiE2YWa8/x/6a6JMPLUf0InvH4=,tag:ct/ChDlsVjWMBsvnah0L5A==,type:str]
token: ENC[AES256_GCM,data:X0n35gfD3uhK6DddtCoOdg3vTYbBZa67JzrsWlgEvYzOiT9lh/7fGh5BeN0SfjzpieNtdUgaio4Gy4s6Ao6OTqc9NOyfQ/syicyIrYUFEllLhWMYYLkEgwYcjMHtBWahU5R9DOXIzNksY0LzL/LgyQTjAZpQiMl6YEPT5FVTRR64GD2U7UzcWEc4ExMvcoWIF66FHYIaEmRR7jshDdkb/VMfmDN2yFJZR6MZl9VriQmaP4K+THc7wQ==,iv:KPwYlKK3l7f9HZGrABNxY7oHj8oB9VvfLXHHVTICrho=,tag:vdqGsnZQ9px32f4trfLw6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17vr37cwjsguh08d5fkaxs3s6dnv9pq6q8qwmmp4ew6t8l6j72plqltuu8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SmhXdkY5OEpEMmJ4VE9w
            R3lGaXpHVHJGNm1XV3NFMW16R0JPdDF3WWs4CndZbEFCaC9EODFDNmh3c1JtUW1j
            eko2T1VNRSszb2syNHBvbENYOTZ6eDQKLS0tIHJzQTZsWU1NL3psS2dqd0dVTTF0
            R3k0TlJLNit3K1dBYnk1M3hlaG1OdG8Kae1HjEvLjlI8613a5r43Fzn2vWwvGieZ
            u0ObMH7Azx20ZfpSdckIM5XuUKw//FH0pYPMAXzVpyjrY4XATnK/rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-07T08:13:47Z"
    mac: ENC[AES256_GCM,data:mZOkad9fONKgSyD/a5gO2na1Oi1a08EAMwDi8V8kzHElU2Z/twG+RLfUprIXSehvsmCWg+WP7IOiejtQZ0hbEitSALe8ecbIuFdJp9UUxAAcis1fNLLZxcsGsL4XSsAWGMA7maUHWno1qCTn1ZlSYUM1tutZfaNHjU2PJ0EBjS4=,iv:+wAcSYiSl9KxiwBH99vZIhwBy6zPuL2KW9/ZdYy2HDE=,tag:CPUdmG82IB5kZWe7NKTRIA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
